### ISSUE TITLE
some refactoring/cleanup needed

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-farmsync#2]
@micgro42 There are a couple of things I'd like to see fixed. I started but it would be great if you could continue when you find the time:
- [x] as talked about, remove the option to sync from farmer, this should make the whole code cleaner I think
- [x] in the util class it seems there are some functions that do basically the same, you should check if they could be streamlined (with above point it might make some things obsolete anyway)
- [x] reordering the functions in that class so that functions that do similar things are next to each other would help readability
- [x] doc blocks are missing, return types are often declared as mixed (which isn't helpful)
- [x] there are dbglog and console.\* calls still in the code, those should go
- [x] I'm not too happy with the need for Reflection to implement an enum type (that is used a lot) -> performance
- [x] there are still non-localized strings left

Otherwise, good work! I like the UpdateResults class hierarchy - very elegant solution.

**Comment by micgro42** [comment]
I would like to keep the `console.dir(jqXHR);` when the ajax request fails. It is comprehensive debug documentation which may be provided by the user in case of an error, but it will not appear unless there actually is an ajax error.

**Comment by micgro42** [comment]
About the enum:

PHP has an built-in enum class in spl, which is the "**S**tandard **P**HP **L**ibrary" http://php.net/manual/en/class.splenum.php

Is it safe to assume that this is available by default in php-installations?

**Comment by micgro42** [comment]
Should be done done now.
